const thesesClasses = [
    {
        id: "2021—2022",
        url: "https://kabk.github.io/go-theses-22/",
        students: [
            "Charlotte van Alfen",
            "Chloé Thiebaut Brayer",
            "Fleurine Brijker",
            "Matas Buckus",
            "Camila Chebez",
            "Dawun Chung",
            "Lisa Dieterle",
            "Petra Eros",
            "Ieva Gailiusaite",
            "Szymon Hernik",
            "Eunseo Hyun",
            "Jules Janssen",
            "Hyeonjeong Joo",
            "Dahsuel Jung",
            "Emir Karyo",
            "Hyobin Kwon",
            "Eunji Lee",
            "Sofia Nikolaeva",
            "Kirill Noskov",
            "Jonas Mindaugas Paberzis",
            "Matteo Pellegrini",
            "Ola Rubik",
            "Pavlo Sharapata",
            "Agnar Freyr Stefánsson",
            "Katla Taylor",
            "Thora Thogersen",
            "Paulina Trzeciak",
            "Weronika Uyar",
            "Paolo Vigliotti",
            "Julia Waraksa",
            "Jan Wojda",
            "Radina Yotova"
        ]
    }, {
        id: "2020—2021",
        url: "https://kabk.github.io/go-theses-21/",
        students: [
            "Yana Abrasheva",
            "Eunjin Ahn",
            "Ocean Albin",
            "Sacha van Alfen",
            "Ivi Apostolatos",
            "Emma Benozzi",
            "Fabiola van den Berg",
            "Ralph Bruens",
            "Daniela Damaschin",
            "Olga Elliot",
            "Isabella Giacomelli",
            "Radek Górniak",
            "Kexin Hao",
            "Eva-Maria Horvath",
            "Michelle Janssen",
            "Handi Kim",
            "Linea Lan Cai Fabricius",
            "Eunji Lee",
            "Kristiana Marija Sproge",
            "Agata Markowska",
            "Merel Meijer",
            "Aurora Navarro Villacampa",
            "Adriana Navarro Villacampa",
            "Tereza Novakova",
            "Ada Popovic",
            "Soyun Park",
            "Karoliina Pärnänen",
            "Vincent Rheinberger",
            "Sjors Rigters",
            "Kilia Robustella",
            "Malik Saïb-Mezghiche",
            "Mika Schalks",
            "Ian Scheufler",
            "Anke Sondi Rumohr",
            "Aliz Soos",
            "Amanda Verberne",
            "Dominik Vrabič Dežman"
        ]
    }, {
        id: "2019—2020",
        url: "https://kabk.github.io/go-theses-20/",
        students: [
            "Emily Anderson",
            "Marc van den Berg",
            "Martijn Brakenhoff",
            "Laura Brouwer",
            "Rafael Colmanetti Correa",
            "Kiki Coster",
            "Yessica Deira",
            "Zahari Dimitrov",
            "Dana Doorenbos",
            "Edward Dżułaj",
            "Louana Gentner",
            "Trang Hà Truong Nguyên",
            "Linda van Houtum",
            "Denise Jansen",
            "Berglind Jóhannsdóttir",
            "Sophia de Jong",
            "Pepijn de Jonge",
            "Nedislav G. Kamburov",
            "Hyeonjeong Kim",
            "Brechje Krah",
            "Selina Landis",
            "Fien Leeflang",
            "Clara Lezla",
            "Maarten Meij",
            "Martin Menso",
            "Anna Moschioni",
            "Nicoletta Radice",
            "Nicolai Schmelling",
            "Tilius Sodeika",
            "Anastasia Umpeleva",
            "Ruben Visser",
            "Seojeong Youn",
            "Mahtab Zamanifar",
            "Zuzanna Zgierska"
        ]
    }, {
        id: "2018—2019",
        url: "https://kabk.github.io/go-theses-19/",
        students: [
            "Artúr Andrási",
            "Katsiaryna Banar",
            "Hilde Barwegen",
            "Leith Benkhedda",
            "Louis Braddock Clarke",
            "Jonathan Cho",
            "Roderick Cornelissen",
            "Mariam Darchiashvili",
            "Sophia de Jong",
            "Linsey Dolleman",
            "Manon Féval",
            "Dominika Fojtikova",
            "Armands Freibergs",
            "Kerrin Go",
            "Céline Hurka",
            "Jan Husstedt",
            "Rully Irawan",
            "Bohwa Jang",
            "Rebecca Joly",
            "Pien Kars",
            "Chris Kore",
            "Risto Kujanpää",
            "Auke Lansink",
            "Kin Mun Chong",
            "Wietske Nutma",
            "Greta Radzevičiūtė",
            "Samuel Rynearson",
            "Kylièn Sarino Bergh",
            "Theresa Scherrer",
            "Cato Stigter",
            "Yeon Sung",
            "Rhodé Tavenier",
            "Lou Top",
            "Carolina Valente Pinto",
            "Peter van Langen",
            "Samantha van Roosenbeek",
            "Evy van Schelt",
            "Nina van Tuikwerd",
            "Esther Vane",
            "Wannes Vrijs",
            "Alfonso Yordi",
            "Roslana Yotova"
        ]
    }, {
        id: "2017—2018",
        url: "https://kabk.github.io/go-theses-18/",
        students: [
            "Nóra Békés",
            "Paul Bille",
            "Carmen Dusmet Carrasco",
            "Daniel Hernández Chacón",
            "Ies De Jong",
            "Jan Egbers",
            "Lukas Engelhardt",
            "André Evers",
            "Elizaveta Glukhova",
            "Michiel Heemskerk",
            "Saber Javanmard",
            "Daan Kars",
            "Dóra Kerekes",
            "Rik Laging",
            "Jungeun Lee",
            "Anna Lenczewska",
            "Zuzanna Loch",
            "Kay Pisarowitz",
            "Taisiia Reshetnik",
            "Rebecca Rui",
            "Joop Schroën",
            "Marika Seo",
            "Alexandra Sukhorukova",
            "Thijmen Van Brunschot",
            "Rudi Van Delden",
            "Niels Van Der Donk",
            "Andreas Van Der Mast",
            "Josephine Van Schende",
            "Lin Ven",
            "Natalia Vishnevskaia"
        ]
    }, {
        id: "2016—2017",
        url: "https://kabk.github.io/go-theses-17/",
        students: [
            "Fay Asselbergs",
            "Remco Blom",
            "Laura de Rijk",
            "Jamie de Rooij",
            "Noa Defesche",
            "Alice Fialova",
            "Katerina Gaidamaka",
            "Amaya Hagelaar",
            "Marton Kabai",
            "Ninthe Kiemeneij",
            "Carmel Klein",
            "Haewon Lim",
            "Carlijn Moerenhout",
            "Manus Nijhoff",
            "Yacinth Pos",
            "Jordy Ringeling",
            "Pascal Schilp",
            "Antonia Schwaiger",
            "Magda Skibinska",
            "Jaap Smit",
            "Sean Valies",
            "Lisa van den Heuvel",
            "Wies van der Wal",
            "Janne van Hooff",
            "Bohye Woo"
        ]
    }, {
        id: "2015—2016",
        url: "https://kabk.github.io/govt-theses-16/",
        students: [
            "Zineb Benassarou",
            "Caitlin Berner",
            "Jana Blom",
            "Evelien Broersen",
            "Martijn de Heer",
            "Jorick de Quaasteniet",
            "Luc Eggenhuizen",
            "Joelle Erkamp",
            "Charlotte Gramberg",
            "Lennart Hendriksma",
            "Rafael Henneberke",
            "Veerle Hoefnagels",
            "Amir Houieh",
            "Gabor Kerekés",
            "Sanne Kloppenburg",
            "Mike Kokken",
            "Tomas Komen",
            "Caroline Langendoen",
            "Haewon Lim",
            "Lisa Moret",
            "Alice Mulder",
            "Naomi Naus",
            "Sophie Neppelenbroek",
            "Elizaveta Pritychenko",
            "Joany Scheeve",
            "Elena Shkarupa",
            "Viktoryia Shydlouskaya",
            "Orphé Tana",
            "Eva van Bemmelen",
            "Vera van de Seyp",
            "Marloes van den Berg",
            "Reni van der Gragt",
            "John van der Meule",
            "Erik van der Veen",
            "Octavia van Horik",
            "Yara Veloso",
            "Marlen Weise",
            "Joeri Woudstra",
            "Christina Yarashevich",
            "Karina Zavidova"
        ]
    }, {
        id: "2014—2015",
        url: "https://kabk.github.io/govt-theses-15/",
        students: [
            "Alyar Aynetchi",
            "Melissa Chan",
            "Nina Couvert",
            "Inês da Costa",
            "Menno de Bruijn",
            "Julian Doove",
            "Rosa Douma",
            "Marius Gottlieb",
            "Sanne Groenendaal",
            "Tomas Laar",
            "Danicha Leliveld",
            "Max Lennarts",
            "Viktorija Liaudanskaite",
            "Rene Louter",
            "Monika Mickutė",
            "Ilse Modder",
            "Wilco Monen",
            "Sepus Noordmans",
            "Regina Pöll",
            "Sander Puhl",
            "Sara Risvåg",
            "Jordie Rovers",
            "Tereza Rullerova",
            "Irene Salo",
            "Edgar Savisaar",
            "Marinus Schepen",
            "Machteld Stoop",
            "Janine Terlouw",
            "Sandra Timmerman",
            "Ieva Valule",
            "Ditmar van Dam",
            "Eline van der Ploeg",
            "Mirte van Kooten",
            "Donna van West",
            "Fedor Velyaminov"
        ]
    }
];